# Generated by Django 4.1.3 on 2022-12-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_details',
            name='humidity',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='crop_details',
            name='ph',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='crop_details',
            name='rainfall',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='crop_details',
            name='temperature',
            field=models.CharField(max_length=20),
        ),
    ]
